name: descrypto
description: A flutter plugin for des crypto.
version: 1.0.0
author: 823812264@qq.com
homepage: https://github.com/zengxiangxin/DesCrypt.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.2
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.geekcarl.descrypto
        pluginClass: DescryptoPlugin
      ios:
        pluginClass: DescryptoPlugin
